# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        name: "[Check Syntax] Check python files syntax"
        types: [ python ]
      - id: check-yaml
        name: "[Check Syntax] Check yaml files syntax"
        args: [ --unsafe ]
        types: [ yaml ]
      - id: check-toml
        name: "[Check Syntax] Check toml files syntax"
        types: [ toml ]
      - id: trailing-whitespace
        name: "[Auto Style] Fix trailing whitespace"
      - id: end-of-file-fixer
        name: "[Auto Style] Fix end of files"
      - id: check-added-large-files
        name: "[Check] Check no large files added"
      - id: check-docstring-first
        name: "[Check Style] Check python modules have docstrings"
        types: [ python ]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
        name: "[Security] Check for secrets leaks"
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: "[Auto Style] Apply black code style"
        args:
          - .
          - --line-length=120
          - --target-version=py311
          - --preview
        types: [ python ]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args:
         - --application-directories
         - .:application:tests/bookshop-test-framework:tests/bookshop-unit-tests:tests/bookshop-api-tests:tests/bookshop-ui-tests
        name: "[Auto Style] Reorder imports"
        types: [ python ]
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.13.0
    hooks:
      - id: pip-compile
        name: "[Auto Dependencies] Pip compile application main requirements"
        files: ^application/(requirements\.txt)|(pyproject\.toml)$
        args:
          - --generate-hashes
          - --output-file=application/requirements.txt
          - --resolver=backtracking
          - --no-emit-trusted-host
          - --quiet
          - --upgrade
          - application/pyproject.toml
      - id: pip-compile
        name: "[Auto Dependencies] Pip compile application dev requirements"
        files: ^application/(dev-requirements\.txt)|(pyproject\.toml)$
        args:
          - --generate-hashes
          - --output-file=application/dev-requirements.txt
          - --resolver=backtracking
          - --no-emit-trusted-host
          - --quiet
          - --upgrade
          - --extra=dev
          - --allow-unsafe
          - application/pyproject.toml
      - id: pip-compile
        name: "[Auto Dependencies] Pip compile test framework main requirements"
        files: ^tests/bookshop-test-framework/(requirements\.txt)|(pyproject\.toml)$
        args:
          - --generate-hashes
          - --output-file=tests/bookshop-test-framework/requirements.txt
          - --resolver=backtracking
          - --no-emit-trusted-host
          - --quiet
          - --upgrade
          - tests/bookshop-test-framework/pyproject.toml
      - id: pip-compile
        name: "[Auto Dependencies] Pip compile test framework dev requirements"
        files: ^tests/bookshop-test-framework/(dev-requirements\.txt)|(pyproject\.toml)$
        args:
          - --generate-hashes
          - --output-file=tests/bookshop-test-framework/dev-requirements.txt
          - --resolver=backtracking
          - --no-emit-trusted-host
          - --quiet
          - --upgrade
          - --extra=dev
          - tests/bookshop-test-framework/pyproject.toml
