default:
  image: python:3.11

include:
  - local: cicd/jobs/build.gitlab-ci.yml
  - local: cicd/jobs/linter.gitlab-ci.yml
  - local: cicd/jobs/unit-tests.gitlab-ci.yml
  - local: cicd/jobs/tests-coverage.gitlab-ci.yml

stages:
  - linter
  - unit-tests
  - tests-coverage

workflow:
  rules:
    # Run pipeline when merge request is open/updated and the target branch is "main".
    - when: never # Never run this pipeline. For debug purposes only. TODO: remove never run before merge
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "main"
      when: never
    - when: always

linter:build:
  stage: linter
  extends: .base_build
  script:
    - !reference [ .build_venv, script ]
    - !reference [ .build_application, script ]
  timeout: 5m


linter:
  stage: linter
  extends: .linter
  needs: ["linter:build"]
  timeout: 5m


unit-tests:build:
  stage: unit-tests
  extends: .base_build
  script:
    - !reference [ .build_test_framework, script ]
    - !reference [ .build_unit_tests, script ]
  timeout: 5m


unit-tests:
  stage: unit-tests
  extends: .unit-tests
  needs: ["unit-tests:build"]
  timeout: 10m


coverage:
  stage: tests-coverage
  extends: .coverage
  timeout: 5m


metrics:
  stage: tests-coverage
  script:
    - cat pylint_metric.txt coverage_metric.txt > metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt
  needs: ["coverage", "linter"]
  timeout: 5m
