.base_build: &base_build_configuration
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/pip
      - venv/
  script: &base_build_script
    - source venv/bin/activate

.build_venv:
  <<: *base_build_configuration
  script:
    - python -m venv venv
    - source venv/bin/activate

.build_application:
  <<: *base_build_configuration
  script:
    - *base_build_script
    - pip install --requirement application/dev-requirements.txt
    - pip install --no-deps --editable "application/.[dev]"

.build_test_framework:
  <<: *base_build_configuration
  script:
    - *base_build_script
    - pip install --requirement tests/bookshop-test-framework/requirements.txt
    - pip install --no-deps tests/bookshop-test-framework

.build_unit_tests:
  <<: *base_build_configuration
  script:
    - *base_build_script
    - pip install --no-deps tests/bookshop-unit-tests

.build_web_api_tests:
  <<: *base_build_configuration
  script:
    - *base_build_script
    - pip install --no-deps "tests/bookshop-api-tests"

.build_web_ui_tests:
  <<: *base_build_configuration
  script:
    - *base_build_script
    - pip install --no-deps "tests/bookshop-ui-tests"
