.base_build: &base_build_configuration
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/pip
      - venv/
  script: &base_build_script
    - source venv/bin/activate

.build_venv:
  <<: *base_build_configuration
  script:
    - python -m venv venv
    - source venv/bin/activate

.build_application:
  <<: *base_build_configuration
  script:
    - *base_build_script
    - pip install --requirement application/dev-requirements.txt
    - pip install --no-deps --editable "application/.[dev]"

.build_test_framework:
  <<: *base_build_configuration
  script:
    - *base_build_script
    - pip install --requirement tests/bookshop-test-framework/requirements.txt
    - pip install --no-deps tests/bookshop-test-framework

.build_unit_tests:
  <<: *base_build_configuration
  script:
    - *base_build_script
    - pip install --no-deps tests/bookshop-unit-tests

.build_web_api_tests:
  <<: *base_build_configuration
  script:
    - *base_build_script
    - pip install --no-deps "tests/bookshop-api-tests"


.install_selenium_driver: &install_selenium_geckodriver
  - |
    SELENIUM_DRIVER_PATH="$VENV_EXECUTION_PATH/$SELENIUM_DRIVER_FILE_NAME"
    if [ ! -f $SELENIUM_DRIVER_PATH ];
    then
      echo "There is no Selenium driver for UI tests. Downloading..."
      geckodriver_gz=$(curl https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep -Eoh 'https.*linux64\.tar\.gz')
      geckodriver_gz=$(echo $geckodriver_gz | cut -f1 -d" ")
      curl -sL "$geckodriver_gz" | tar -xz --checkpoint=.10
      chmod +x geckodriver
      mv geckodriver $SELENIUM_DRIVER_PATH
      echo "Selenium driver downloaded to $SELENIUM_DRIVER_PATH"
      cp $SELENIUM_DRIVER_PATH /usr/local/bin
    fi

.build_web_ui_tests:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/pip
      - venv/
      - /opt/firefox/
  variables:
    SELENIUM_DRIVER_FILE_NAME: "geckodriver"
    VENV_EXECUTION_PATH: "venv/bin"
  <<: *base_build_configuration
  script:
    - *base_build_script
    - *install_selenium_geckodriver
    - pip install --no-deps "tests/bookshop-ui-tests"
