variables:
  MINIMUM_UNIT_TESTS_COVERAGE_SCORE:
    description: "Minimum unit tests coverage score to pass Unit Tests Coverage Quality Gate"
    value: "75"


.coverage:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - venv/
      - .coverage
  script:
    - source venv/bin/activate
    - coverage xml -o tests-coverage-xml-report.xml
    - COVERAGE_PERCENT=$(coverage report --format total)
    - coverage report
    - echo "tests-coverage $COVERAGE_PERCENT%" > coverage_metric.txt
    - echo "Code coverage - $COVERAGE_PERCENT"
    - > 
      if (( $COVERAGE_PERCENT > $MINIMUM_UNIT_TESTS_COVERAGE_SCORE ));
      then 
        echo "Unit Tests Coverage Quality Gate passed. Current: $COVERAGE_PERCENT. Expected: >$MINIMUM_UNIT_TESTS_COVERAGE_SCORE"
        exit 0
      else
        echo "Unit Tests Coverage Quality Gate failed. Current: $COVERAGE_PERCENT. Expected: >$MINIMUM_UNIT_TESTS_COVERAGE_SCORE" 
        exit 1
      fi
  coverage: '/Code coverage - \d+\.\d+/'
  artifacts:
    paths:
      - coverage_metric.txt
    reports:
      coverage_report:
        coverage_format: cobertura
        path: tests-coverage-xml-report.xml
    expire_in: 1 week
