.ui-tests:
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - venv/
  services:
    - name: selenium/standalone-firefox:latest
      alias: firefox
  script:
    - source venv/bin/activate
    - echo "Running application in TESTING environment"
    - cd application/bookshop_app
    - ENV="TESTING" run_bookshop_app &
    - echo "Waiting application to warm up 5 seconds..." && sleep 5s
    - cd ../..
    - echo "Running WEB UI tests..."
    - |
      ENV="TESTING" \
      REMOTE_WEB_DRIVER_URL="http://firefox:4444/wd/hub" \
      pytest tests/bookshop-ui-tests/bookshop_ui_tests \
      --junitxml ui-tests-junit-report.xml
  artifacts:
    paths:
      - ui-tests-junit-report.xml
    reports:
      junit: ui-tests-junit-report.xml
    expire_in: 1 week
